# Generated by Django 5.2.7 on 2025-11-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='aforo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='anyo_fundacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
